### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'cache'

### ISSUE THREAD

**Issue by malhunters** [PayloadSecurity/VxAPI#38]
Hi,

I have facing following issue:

<<< During the code execution, error has occurred. Please try again or contact the support. >>>

Message: '[WinError 2] The system cannot find the file specified: 'cache''.

Traceback (most recent call last):
  File "vxapi.py", line 396, in main
    cli_manager.run()
  File "vxapi.py", line 298, in run
    current_key_json, current_key_response_headers = self.get_current_key_data()
  File "vxapi.py", line 280, in get_current_key_data
    self.write_current_key_data_to_cache(current_key_cli_object)
  File "vxapi.py", line 290, in write_current_key_data_to_cache
    CliFileWriter.write(os.path.dirname(self.current_key_sess_cache_file_path), os.path.basename(self.current_key_sess_cache_file_path), json.dumps({'timestamp': int(time.time()), 'response': current_key_json, 'headers': dict(current_key_response_headers)}))
  File "C:\Users\User\Desktop\VxAPI-master\cli\cli_file_writer.py", line 12, in write
    CliFileWriter.create_dir_if_not_exists(dir_path)
  File "C:\Users\User\Desktop\VxAPI-master\cli\cli_file_writer.py", line 45, in create_dir_if_not_exists
    os.makedirs(dir_path)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'cache'

**Comment by kkochanski** [comment]
Hi, 

Unfortunately, we were not able to reproduce the current issue, but highly probably it's connected with  relative path handling during save/retrieval - that was improved in the latest commit - https://github.com/PayloadSecurity/VxAPI/commit/7d70d4fc75fe7f16efbb80a0a606792d42362ae1

Can I ask you for check if it fixes your issue?

**Comment by kkochanski** [comment]
Closing due to missing activity.
